name: Test Generate Anki Decks

on:
  push:
    branches-ignore: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: install graphviz
      run: sudo apt install graphviz
    - name: pip install
      run: pip3 install genanki graphviz
    - name: Test generate Decks
      run: python3 generate.py
